// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3nVQba7ihOGZGFj229eViU_DUlxQ9cM',
    appId: '1:540704325848:web:1aee15b9034efc68c617ad',
    messagingSenderId: '540704325848',
    projectId: 'bookstoresproject',
    authDomain: 'bookstoresproject.firebaseapp.com',
    storageBucket: 'bookstoresproject.appspot.com',
    measurementId: 'G-1F6R58NQ3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARY-SEvd7U-eLAh6qvNp8PDPWbVGcdimo',
    appId: '1:540704325848:android:f316aad6f80f7ca3c617ad',
    messagingSenderId: '540704325848',
    projectId: 'bookstoresproject',
    storageBucket: 'bookstoresproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6uGX8Gx4N6V_IXeY7-GCBJQDib0HdQTo',
    appId: '1:540704325848:ios:41992177a5277ce4c617ad',
    messagingSenderId: '540704325848',
    projectId: 'bookstoresproject',
    storageBucket: 'bookstoresproject.appspot.com',
    iosClientId: '540704325848-ojl13ca40caf5riodk05mn931d3ovf3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6uGX8Gx4N6V_IXeY7-GCBJQDib0HdQTo',
    appId: '1:540704325848:ios:4cb11f201c8c0f67c617ad',
    messagingSenderId: '540704325848',
    projectId: 'bookstoresproject',
    storageBucket: 'bookstoresproject.appspot.com',
    iosClientId: '540704325848-d5hjug2if8a3eu1s3j9hcj4gubfp542d.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore.RunnerTests',
  );
}
